=== Arsh-Sandhu/vLEI/schema/acdc/gleif-vLEI-credential.json
{
  "$id": "Ek6vA-fVXDRbraVi7a9ydKStHiByUoF37Cgz4L58LWds",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "GLEIFvLEICredential",
  "type": "object",
  "properties": {
    "v": {
      "type": "string"
    },
    "i": {
      "type": "string"
    },
    "ti": {
      "type": "string"
    },
    "x": {
      "description": "schema block",
      "type": "string"
    },
    "d": {
      "description": "data block",
      "properties": {
        "i": {
          "type": "string"
        },
        "si": {
          "type": "string"
        },
        "issuanceDate": {
          "format": "date-time",
          "type": "string"
        },
        "credentialStatus": {
          "type": "string"
        },
        "LEI": {
          "type": "string"
        },
        "type": {
          "contains": {
            "const": "GLEIFvLEICredential"
          },
          "type": "array"
        }
      },
      "additionalProperties": false,
      "required": [
        "i",
        "issuanceDate",
        "credentialStatus",
        "LEI",
        "type"
      ],
      "type": "object"
    }
  },
  "additionalProperties": false,
  "required": [
    "i",
    "d"
  ]
}

=== Arsh-Sandhu/vLEI/samples/acdc/gleif-vLEI-credential.json
{
  "v": "ACDC10JSON00011c_",
  "i": "Esmy31gPoOJzxv2JwpGBb_zJ7XkNUVYZZheMifW89CQY",
  "ti": "did:keri:ELzvA4arGVUFitOpSCjWvmpfVzTmJR4wIVnsnRtlCPG",
  "x": "Ek6vA-fVXDRbraVi7a9ydKStHiByUoF37Cgz4L58LWds",
  "d": {
    "i": "ErmVM5JGLewHJrSqIuhwWktoIlfffh7sHIGAQvtcFSU",
    "si": "did:keri:Eky8a1Xo48shGZobJA2C_NGVXK59P04mY9QmWEbflHBM",
    "issuanceDate": "2021-06-09T17:35:54.169967+00:00",
    "credentialStatus": "did:keri:EymRy7xMwsxUelUauaXtMxTfPAMPAI6FkekwlOjkggt",
    "LEI": "254900OPPU84GM83MG36",
    "type": [
      "VerifiableCredential",
      "GLEIFvLEICredential"
    ]
  }
}

=== Arsh-Sandhu/vLEI/samples/acdc/qualified-vLEI-issuer-vLEI-credential.json
{
  "v": "ACDC10JSON00011c_",
  "i": "EYo4R9I08Et5H5SWKG8ZMS83r8FmRtfahN0V9NbG9zdw",
  "ti": "did:keri:Ei5csblWpTy22uVkbZrZxvSUORxPvIlrfpq2e1hKTtfA",
  "x": "ECcj1CBn4dpo6ZOmZQNtAjXxT4_MsVXipt5VTPjvSAf0",
  "d": {
    "i": "Ea4ny_YZAtAGUwGSyH7iFiKjpM3yFiDHcjrdomqt7Ryk",
    "si": "did:keri:EP2ukuiw_0xcp943NWz4IRnNtxwx7rzROwV1D_ZRP0XQ",
    "issuanceDate": "2021-06-09T17:35:54.169967+00:00",
    "credentialStatus": "did:keri:EymRy7xMwsxUelUauaXtMxTfPAMPAI6FkekwlOjkggt",
    "LEI": "5493001KJTIIGC8Y1R12",
    "type": [
      "VerifiableCredential",
      "QualifiedvLEIIssuervLEICredential"
    ]
  }
}
