=== Arsh-Sandhu/vLEI/schema/acdc/legal-entity-vLEI-credential.json
{
  "$id": "E-BRq9StLuC9DxGgiFiy2XND0fFgzyn8cjptlcdvGEFY",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Legal Entity vLEI Credential",
  "description": "A vLEI Credential issued by a Qualified vLEI issuer to a Legal Entity",
  "properties": {
    "v": {
      "type": "string"
    },
    "i": {
      "type": "string"
    },
    "ti": {
      "type": "string"
    },
    "x": {
      "description": "schema block",
      "type": "string"
    },
    "d": {
      "description": "data block",
      "properties": {
        "i": {
          "type": "string"
        },
        "si": {
          "type": "string"
        },
        "issuanceDate": {
          "format": "date-time",
          "type": "string"
        },
        "credentialStatus": {
          "type": "string"
        },
        "LEI": {
          "type": "string"
        },
        "type": {
          "contains": {
            "const": "LegalEntityvLEICredential"
          },
          "type": "array"
        }
      },
      "additionalProperties": false,
      "required": [
        "i",
        "issuanceDate",
        "credentialStatus",
        "LEI",
        "type"
      ],
      "type": "object"
    },
    "s": {
      "contains": {
        "type": "object"
      },
      "description": "source block",
      "items": {
        "properties": {
          "qualifiedvLEIIssuervLEICredential": {
            "type": "string"
          }
        },
        "additionalProperties": false,
        "required": [
          "qualifiedvLEIIssuervLEICredential"
        ],
        "type": "object"
      },
      "maxItems": 1,
      "minItems": 1,
      "type": "array"
    }
  },
  "additionalProperties": false,
  "required": [
    "i",
    "s",
    "d"
  ],
  "type": "object"
}

=== Arsh-Sandhu/vLEI/samples/acdc/legal-entity-vLEI-credential.json
{
  "v": "ACDC10JSON00011c_",
  "i": "EBdXt3gIXOf2BBWNHdSXCJnFJL5OuQPyM5K0neuniccM",
  "ti": "did:keri:EmkPreYpZfFk66jpf3uFv7vklXKhzBrAqjsKAn2EDIPM",
  "x": "E46jrVPTzlSkUPqGGeIZ8a8FWS7a6s4reAXRZOkogZ2A",
  "d": {
    "i": "EgveY4-9XgOcLxUderzwLIr9Bf7V_NHwY1lkFrn9y2PY",
    "si": "did:keri:EQzFVaMasUf4cZZBKA0pUbRc9T8yUXRFLyM1JDASYqAA",
    "issuanceDate": "2021-06-09T17:35:54.169967+00:00",
    "credentialStatus": "did:keri:EymRy7xMwsxUelUauaXtMxTfPAMPAI6FkekwlOjkggt",
    "LEI": "254900OPPU84GM83MG36",
    "type": [
      "VerifiableCredential",
      "LegalEntityvLEICredential"
    ]
  },
  "s": [
    {
      "qualifiedvLEIIssuervLEICredential": "EBDmgKOAEwnMGsofWg2m0l63J1awfJafqJyCzTnVkdSw"
    }
  ]
}
