=== Arsh-Sandhu/vLEI/schema/acdc/legal-entity-engagement-context-role-vLEI-credential.json
{
    "$id": "Eahe926WIhnUc5neeBhcTLkuyUdd4eyZuur90tWecBG4",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "additionalProperties": false,
    "properties": {
        "d": {
            "additionalProperties": false,
            "description": "data block",
            "properties": {
                "LEI": {
                    "type": "string"
                },
                "credentialStatus": {
                    "type": "string"
                },
                "engagementContextRole": {
                    "type": "string"
                },
                "i": {
                    "type": "string"
                },
                "issuanceDate": {
                    "format": "date-time",
                    "type": "string"
                },
                "personLegalName": {
                    "type": "string"
                },
                "type": {
                    "contains": {
                        "const": "LegalEntityEngagementContextRolevLEICredential"
                    },
                    "type": "array"
                }
            },
            "required": [
                "i",
                "LEI",
                "credentialStatus",
                "issuanceDate",
                "type",
                "personLegalName",
                "engagementContextRole"
            ],
            "type": "object"
        },
        "i": {
            "type": "string"
        },
        "s": {
            "contains": {
                "type": "object"
            },
            "description": "source block",
            "items": {
                "additionalProperties": false,
                "properties": {
                    "qualifiedvLEIIssuervLEICredential": {
                        "type": "string"
                    }
                },
                "required": [
                    "qualifiedvLEIIssuervLEICredential"
                ],
                "type": "object"
            },
            "maxItems": 1,
            "minItems": 1,
            "type": "array"
        },
        "ti": {
            "type": "string"
        },
        "x": {
            "description": "schema block",
            "type": "string"
        }
    },
    "required": [
        "i",
        "s",
        "d"
    ],
    "type": "object"
}

=== Arsh-Sandhu/vLEI/samples/acdc/legal-entity-engagement-context-role-vLEI-credential.json
{
  "i": "EGtyThM1rLBSMZ_ozM1uAnFvSfC0N1jaQ42aKU5sHYTGFD",
  "x": "EZllThM1rLBSMZ_ozM1uAnFvSfC0N1jaQ42aKU5sCZ5Q",
  "s": [
    {
      "qualifiedvLEIIssuervLEICredential": "EGtyThM1rLBSMZ_ozM1uAnFvSfC0N1jaQ42aKU5sHYTGFD"
    }
  ],
  "d": {
    "type": [
      "VerifiablePresentation",
      "LegalEntityEngagementContextRolevLEICredential"
    ],
    "LEI": "254900YH3ZCDPE1E5306",
    "personLegalName": "Anne Jones",
    "engagementContextRole": "Project Manager",
    "credentialStatus": "did:keri:EymRy7xMwsxUelUauaXtMxTfPAMPAI6FkekwlOjkggt",
    "issuanceDate": "2021-06-09T17:35:54.169967+00:00",
    "i": "ErmVM5JGLewHJrSqIuhwWktoIlfffh7sHIGAQvtcFSU"
  }
}
