=== Arsh-Sandhu/vLEI/schema/common/gleif-vLEI-credential.json
{
    "$id": "EtK5g3YBaExiY2JD4o95xvmDyktS6IlqeMYC202_xA88",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "properties": {
        "credentialStatus": {
            "properties": {
                "id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            },
            "required": [
                "id"
            ],
            "type": "object"
        },
        "credentialSubject": {
            "additionalProperties": false,
            "properties": {
                "LEI": {
                    "type": "string"
                }
            },
            "required": [
                "LEI"
            ],
            "type": "object"
        },
        "issuanceDate": {
            "format": "date-time",
            "type": "string"
        },
        "issuer": {
            "type": "string"
        },
        "type": {
            "type": "array"
        }
    },
    "required": [
        "type",
        "issuer",
        "issuanceDate",
        "credentialSubject",
        "credentialStatus"
    ],
    "type": "object"
}

=== Arsh-Sandhu/vLEI/samples/common/gleif-vLEI-credential.json
{
  "credentialSubject": {
    "LEI": "254900OPPU84GM83MG36"
  },
  "issuer": "EGtyThM1rLBSMZ_ozM1uAnFvSfC0N1jaQ42aKU5sHYTGFD",
  "credentialStatus": {
    "id": "did:keri:EymRy7xMwsxUelUauaXtMxTfPAMPAI6FkekwlOjkggt"
  },
  "issuanceDate": "2019-05-23T04:00:00.0Z",
  "type": [
    "VerifiableCredential",
    "GLEIvLEICredential"
  ]
}
