=== Arsh-Sandhu/vLEI/schema/common/legal-entity-engagement-context-role-vLEI-credential.json
{
  "$id": "EsAhmFShdnoXHBQywsLdxup7Rq8_eSd-B1huca-fF-ps",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "properties": {
    "credentialStatus": {
      "properties": {
        "id": {
          "type": "string"
        },
        "type": {
          "type": "string"
        }
      },
      "required": [
        "id"
      ],
      "type": "object"
    },
    "credentialSubject": {
      "properties": {
        "LEI": {
          "type": "string"
        },
        "engagementRoleContext": {
          "type": "string"
        },
        "personLegalName": {
          "type": "string"
        },
        "qualifiedvLEIIssuervLEICredential": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "LEI",
        "personLegalName",
        "engagementRoleContext",
        "qualifiedvLEIIssuervLEICredential"
      ],
      "type": "object"
    },
    "issuanceDate": {
      "format": "date-time",
      "type": "string"
    },
    "issuer": {
      "type": "string"
    },
    "type": {
      "contains": {
        "const": "LegalEntityEngagementContextRolevLEICredential"
      },
      "type": "array"
    }
  },
  "required": [
    "type",
    "issuer",
    "issuanceDate",
    "credentialSubject",
    "credentialStatus"
  ],
  "type": "object"
}

=== Arsh-Sandhu/vLEI/samples/common/legal-entity-engagement-context-role-vLEI-credential.json
{
  "credentialSubject": {
    "LEI": "254900OPPU84GM83MG36",
    "personLegalName": "Karla McKenna",
    "engagementRoleContext": "Head of Standards",
    "qualifiedvLEIIssuervLEICredential": "EYdjd3TMjapXptVvyXARrsfpOtaIaY4HuvaHHkgVSvW"
  },
  "issuer": "EGtyThM1rLBSMZ_ozM1uAnFvSfC0N1jaQ42aKU5sHYTGFD",
  "credentialStatus": {
    "id": "did:keri:EymRy7xMwsxUelUauaXtMxTfPAMPAI6FkekwlOjkggt"
  },
  "issuanceDate": "2019-05-23T04:00:00.0Z",
  "type": [
    "VerifiablePresentation",
    "LegalEntityEngagementContextRolevLEICredential"
  ]
}
